### ISSUE TITLE
x-cluster to allow changing cluster provisioning configuration.

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#120]
As an ECS user, I want to be able to define the cluster capacity providers for my cluster.

```
x-cluster:
  Properties:
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      ClusterName: Name
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE_SPOT
          Weight: 2
        - CapacityProvider: FARGATE
          Weight: 1
```

In the future, I would like to be able to define an ASG to add as a Capacity Provider.
By default, I would like to use FARGATE and FARGATE_SPOT if not provided.
