### ISSUE TITLE
Allow for extra IAM permissions to be given to the service

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#139]
In addition to access to SQS etc, I would like my container to have access to other services on AWS I need IAM access for.

**Describe the solution you'd like**
```
x-configs:
  iam:
    boundary: abcd
    managed_policies:
      - policyArn
    policies:
      - name: abcd
        document: {}
```
