### ISSUE TITLE
Set CW Logs retention

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#165]
**Is your feature request related to a problem? Please describe.**
I want to be able to set the logs retention for the service directly from the docker-compose file.

**Describe the solution you'd like**
```
services:
  abcd:
    x-aws-logging:
      retention_period: 14
```
