### ISSUE TITLE
Adding load balancer causes ecs_composex up  to fail

### ISSUE THREAD

**Issue by delahayethierry** [lambda-my-aws/ecs_composex#175]
**Describe the bug**

Issue when creating stack that needs a load balancer.

**To Reproduce**
1. How you installed ECS ComposeX'...'
2. How you are executing it ? : As a CLI tool, as a library, in lambda?
3. Link / share your Docker compose file

1. Installed ECS ComposeX with "pip install ecs_composex" with python 3.7

2. We execute it as part of a shell script:
`ecs_composex up -f docker_compose.yml -d outputs -n outputname -b dashboard-cfn-templates`

3. Docker compose file (with project name replaced):

```
x-configs:
  project-forecast:
    network:
      is_public: True
      lb_type: network
      use_cloudmap: True

services:
  project-forecast:
    environment:
      NAME: DASHBOARD
    image: accountnb.dkr.ecr.eu-west-1.amazonaws.com/project-folder/project-forecast:latest
    ports:
      - 80:80
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: "1"
          memory: "2048M"

x-tags:
  - name: project
    value: project-forecast
```

**Expected behavior**

We'd expect the shell script to create the stack on AWS cloudformation

**Logs**
If applicable, add logs of errors using from ECS ComposeX

```
2020-08-25 15:15:28 [INFO], No x-vpc detected. Creating a new VPC.
2020-08-25 15:15:28 [INFO], cluster.lan
Traceback (most recent call last):
  File “/Users/user/dev/1a/covid-19/dashboard/venv/bin/ecs_composex”, line 10, in <module>
    sys.exit(main())
  File “/Users/user/dev/1a/covid-19/dashboard/venv/lib/python3.7/site-packages/ecs_composex/cli.py”, line 179, in main
    root_stack = generate_full_template(settings)
  File “/Users/user/dev/1a/covid-19/dashboard/venv/lib/python3.7/site-packages/ecs_composex/ecs_composex.py”, line 331, in generate_full_template
    root_stack, settings, vpc_stack, dns_settings.nested_params, create_cluster
  File “/Users/user/dev/1a/covid-19/dashboard/venv/lib/python3.7/site-packages/ecs_composex/ecs_composex.py”, line 268, in create_services
    stack = ServicesStack(“services”, settings)
  File “/Users/user/dev/1a/covid-19/dashboard/venv/lib/python3.7/site-packages/ecs_composex/ecs/__init__.py”, line 113, in __init__
    services = generate_services(settings, cluster_sg)
  File “/Users/user/dev/1a/covid-19/dashboard/venv/lib/python3.7/site-packages/ecs_composex/ecs/ecs_template.py”, line 328, in generate_services
    services = handle_families_services(families, cluster_sg, settings)
  File “/Users/user/dev/1a/covid-19/dashboard/venv/lib/python3.7/site-packages/ecs_composex/ecs/ecs_template.py”, line 292, in handle_families_services
    settings=settings,
  File “/Users/user/dev/1a/covid-19/dashboard/venv/lib/python3.7/site-packages/ecs_composex/ecs/ecs_service.py”, line 363, in __init__
    self.define_service_ingress(settings)
  File “/Users/user/dev/1a/covid-19/dashboard/venv/lib/python3.7/site-packages/ecs_composex/ecs/ecs_service.py”, line 785, in define_service_ingress
    service_lb = self.add_service_load_balancer(settings)
  File “/Users/user/dev/1a/covid-19/dashboard/venv/lib/python3.7/site-packages/ecs_composex/ecs/ecs_service.py”, line 722, in add_service_load_balancer
    service_lb = self.add_load_balancer(settings)
  File “/Users/user/dev/1a/covid-19/dashboard/venv/lib/python3.7/site-packages/ecs_composex/ecs/ecs_service.py”, line 644, in add_load_balancer
    self.add_public_ips(settings.aws_azs)
  File “/Users/user/dev/1a/covid-19/dashboard/venv/lib/python3.7/site-packages/ecs_composex/ecs/ecs_service.py”, line 518, in add_public_ips
    f”EipPublicNlb{az.replace(‘-’, ‘’).strip()}{self.service_name}“,
AttributeError: ‘dict’ object has no attribute ‘replace’
```

**Desktop (please complete the following information):**
 - OS: [e.g. Fedora/Windows/Mac]
 - Python version (3.6,3.7,3.8)
 - If you were doing things from a branch, which one?
 - Commit ID ?
 - Tag/Version?

OS: Ubuntu 18.04, python version 3.7, latest ecs_composex version
