### ISSUE TITLE
Enable litteral Sub and Ref in Env vars

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#182]
**Is your feature request related to a problem? Please describe.**
As a developer I would want to be able to set an env var and use the native CFN sub functions to substitute values in CFN.

**Describe the solution you'd like**

```
services:
  serviceA:
    environment:
      accountId: ${AWS::AccountId}"
      endpoint:  "s3.${AWS::Region}.${AWS::URLSuffix}"
```

In the template translates as 

`accountId: !Sub "${AWS::AccountId}"`
`endpoint: !Sub "s3.${AWS::Region}.${AWS::URLSuffix}"`
