### ISSUE TITLE
Support for AWS::Kinesis::Stream

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#205]
As a developer I would like the ability to define a new Kinesis Stream that my application gets access to.

**Describe the solution you'd like**
```
x-kinesis.stream:
  streamA:
    Properties: {}
    Settings: {}
    Services: []

```
