### ISSUE TITLE
x-rds Lookup/Use support

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#206]
As a developer I might already have created a database in production, outside of ComposeX.
I would like to be able to identify a pre-existing DB and its secret and associate it to my services.

**Describe the solution you'd like**
```
x-rds:
  dbA:
    Lookup:
      Tags:
         - key: Value
       Secret:
         Tags:
           - key: Value
         Name: "secret/name/in/secrets-manager"

```
**Describe alternatives you've considered**

```
x-rds:
  dbA:
    Lookup:
      Tags:
        - key: Value
    Secret:
      - dbasecret

secrets:
  dbasecret:
    x-secrets:
      Name: "secret/name/in/secrets-manager"

```

In the second syntax, we are re-using the docker-compose `secrets` and if associated to a DB we would automatically add it to the service definition.
