### ISSUE TITLE
Cooldown for SQS Scaling

### ISSUE THREAD

**Issue by jackqu7** [lambda-my-aws/ecs_composex#220]
**Is your feature request related to a problem? Please describe.**
I would like to change the cooldown period for my SQS scaling rules from the default of 300 seconds.

**Describe the solution you'd like**
```      
- name: myservice
  access: RWMessages
  scaling:
    cooldown: <N>
    steps:
      - lower_bound: 0
        upper_bound: 3000
        count: 1
```

**Comment by JohnPreston** [comment]
Thanks for that FR

Here is the latest implementation changes
```
- name: myservice
  access: RWMessages
  scaling:
    scale_in_cooldown: <N>
    scale_out_cooldown: <N>
    steps:
      - lower_bound: 0
        upper_bound: 3000
        count: 1
```
Allowing to distinguish cool downs
