### ISSUE TITLE
x-rds::New-MacroParameter::MultiAz: True/False

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#225]
**Is your feature request related to a problem? Please describe.**

I want to deploy a RDS (Aurora or regular MySQL/PSQL) cluster in multi AZ and I want it to be simple.
For AWS RDS Aurora, I would define a number of replica nodes too.

**Describe the solution you'd like**

```
x-rds:
  dbA:
    Properties:
      MultiAz: True/False
```

**Describe alternatives you've considered**
```
x-rds:
  dbA:
    MacroParameters:
      MultiAz: True/False
      ReplicaNodes: <N>
```

**Additional context**
RDS Instance MultiAZ property

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-multiaz
