### ISSUE TITLE
Cross Account lookups

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#226]
**Is your feature request related to a problem? Please describe.**
I use ComposeX in my CICD pipeline which spans across multiple accounts.
I would like to be able to indicate an IAM role to use in order to perform the API calls to Lookup and find resources in another account.

**Describe the solution you'd like**
```
composex --role-arn arn:aws:iam::012345678912:role/my-remote-role
```

**Describe alternatives you've considered**
```
x-configs:
  iam:
    role_arn: arn:aws:iam::012345678912:role/my-remote-role
```
The alternative solution would allow to have the IAM role defined within the composeX files.
Additional alternative, more complex though
```
x-resource:
  resource:
    Lookup:
     Tags: []
      role_arn: arn:aws:iam::012345678912:role/my-remote-role
```
Would indicate to use that role for this specific resource only.
