### ISSUE TITLE
x-rds User - auto provision new user secret and create PSQL access to schemas etc. for this user.

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#235]
**Is your feature request related to a problem? Please describe.**
As a developer I would like to not use the root admin password to access the DB and have an application specific username/password that would grant me access to a set of schemas/tables/dbs 

**Describe the solution you'd like**
```
x-rds:
  dbA:
    Services:
      - name: app01
        access:
          create_app_user: True/False
          rotate_every: 31d
          psql:
            schemas: [] 
```
The outcome is, I have a new Secret in secrets manager for my own user, this secret gets rotated. Ideally I would like something smart handling containers recycling when a new secret is set via SecretsManager rotation.
