### ISSUE TITLE
x-resources::Settings::Attributes

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#246]
**Is your feature request related to a problem? Please describe.**
As a developer deploying some resources via ComposeX, I might want some attributes of resources, supported in CFN, and get that exposed to the Environment of my container as well / instead of the default defined.

For example, for SQS queues, if I want the ARN instead of the URL

**Describe the solution you'd like**
```
x-sqs:
  queueA:
    Settings:
      EnvNames: ["QUEUE_A" ,"queue_a"]
      Attributes: ["QueueName", "Arn"]
```
Here this would result in the following in my ContainerDefinition

```
Environment:
 - Name: QUEUE_A_QueueName
   Value: !GetAtt queueA.QueueName
-  Name: QUEUE_A_Arn
   Value: !GetAtt queueA.Arn
[so on for queue_a]
```
If the list is empty, keep the default behaviour of ComposeX

For reference, SQS queue Attributes are [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html) => Return Values.
