### ISSUE TITLE
x-acm::MacroParameters::DnsNames

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#249]
**Is your feature request related to a problem? Please describe.**
As a developer I just want to create a new ACM cert and have it attached to my ALB/NLB.
It's be easier for me to just give a list of the domains I want the cert to use, in a list, and the first one is the CN

**Describe the solution you'd like**
```
x-acm:
  public-cert-01:
    Properties: {}
    MacroParameters:
      DnsNames:
         - mymaincn.domain.tld
         - alternate01.domain.tld
         - alternate.02.domain.tld
x-dns:
  PublicZone:
    Use: ZABCD0123
```
Using the x-dns/PublicZone/Use or Lookup property, it will use the HostedZoneID and pass it on for all validation.
