### ISSUE TITLE
services::x-configs::Ingress::Services

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#264]
**Is your feature request related to a problem? Please describe.**
When **not using AppMesh** I want the ability to easily define dependency between services at the network level.
Sometimes, it is required for a service that another has started, so I would rather have a wait on it before starting the other service (*from a different family*).

**Describe the solution you'd like**

```
services:
  serviceA: {}
  serviceB:
    x-configs:
      Ingress:
        Services:
          - Name: serviceA
            DependsOn: True/False
```

**Describe alternatives you've considered**
```
services:
  serviceA: {}
  serviceB:
    depends_on:
      - serviceA
    x-configs:
      Ingress:
        Services:
          - Name: serviceA
```

In both cases, serviceB should not start before serviceA is up and running, and the ingress rule must be done before the serviceB starts.
