### ISSUE TITLE
use attribute specific x-key at service level instead of x-configs

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#267]
**Is your feature request related to a problem? Please describe.**
At the moment, everything is defined inside x-configs (iam, scaling etc.).
Instead of having to put everything underneath x-configs, I would like to be able to use x-(config key)

**Describe the solution you'd like**
```
services:
  serviceA:
    x-configs:
     iam: {}
     scaling: {}
```
becomes

```
services:
  serviceA:
    x-scaling: {}
    x-iam: {}
```
