### ISSUE TITLE
Allow custom networks definition and place containers in matching subnets

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#277]
**Is your feature request related to a problem? Please describe.**
As a developer I might have applications with different network needs in terms of access. In AWS, I might have different subnets which illustrate these.

Currently in ComposeX I can define x-vpc and 3 subnets categories (Public, App, Storage).
I would like to be able to create new network definitions and be able to have `Use` and `Lookup` (this FR does not concern creation of new VPC).

**Describe the solution you'd like**
```
x-vpc:
  Lookup:
    VpcId: {}
    AppSubnets: {}
    PublicSubnets: {}
    StorageSubnets: {}
    CustomDefined {}


services:
  serviceA:
    x-network:
      SubnetsGroup: CustomDefined
```

**Describe alternatives you've considered**
Using docker-compose native networks, users can map the subnet category to the docker network
```

x-vpc:
  Lookup:
    VpcId: {}
    AppSubnets: {}
    PublicSubnets: {}
    StorageSubnets: {}
    CustomDefined {}

networks:
  public:
    driver: {} # docker-compose native network options
    x-vpc: PublicSubnets
  custom:
   x-vpc: CustomDefined

services:
  serviceA:
    networks:
      - public
  serviceB:
    networks:
      - custom
```

Note:: if someone defines more than one docker-compose network for a single service, composex should consider the first one only.

**Additional context**
https://docs.docker.com/compose/networking/
https://docs.docker.com/compose/compose-file/#networks
