### ISSUE TITLE
docker-compose env_file support

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#281]
**Is your feature request related to a problem? Please describe.**
As a developer I would like to be able to automatically publish files in S3 marked in env_files.
Given ECS ComposeX uploads template files and config files already, I would like for these env files to be uploaded along the templates.

**Describe the solution you'd like**
```
services:
  serviceA:
    env_file: bla
   serviceB:
      env_file:
        - fileA
        - fileB
```
**Additional context**
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-environmentfiles
