### ISSUE TITLE
x-elbv2::MacroParameters::Route53

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#284]
**Is your feature request related to a problem? Please describe.**
As a developer using an ALB/NLB via elbv2 and defined a x-dns PublicZone I would like to be able to define one or more CNAMEs or Aliases that will point to that ALB/NLB

**Describe the solution you'd like**
```
x-elbv2:
  lbA:
    MacroParameters:
      Route53:
      ZoneId: ZABCD (or if not set, use x-dns/PublicZone)
      Aliases: []
      CNAMEs: []
```

**Comment by JohnPreston** [comment]
Counter proposal: allow people to define Route53 recordsets. This would allow for a better generic definition.
When it comes to targets that support to be an [AliasTarget](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget-1.html) then the AliasTarget property is set for that defined `Target`.
If no `Target` is set, just use the properties as defined and needs to be valid.
If and when the `Target` is defined and points to one of the resources, some Properties might be overriden.

```
x-elbv2:
  lbvA: {}

x-s3:
  bucketA: {}

x-dns:
  Records:
   - Properties: {} # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html
     Target: x-elbv2::lbA
  - Properties: {}
    Target: x-s3::bucketA
```
