### ISSUE TITLE
x-dns::Records for Public DNS records creation pointing to AWS resources

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#290]
**Is your feature request related to a problem? Please describe.**
As a developer I like to give friendly DNS Names for my applications. Currently in composex, I have to use the ELB DNS Name and such which is not great especially if I keep creating new environments.

I would also like in the future to be able to point to CloudFront distributions or S3 buckets with static website enabled.

**Describe the solution you'd like**
```
x-elbv2:
  lbA: {}

x-dns:
  Records:
    - Properties: {} # AWS Route53 properties for record set
      Target: x-elbv2::lbA
```
 
RecordSet : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html
