### ISSUE TITLE
Incorrect container marked as essential

### ISSUE THREAD

**Issue by jackqu7** [lambda-my-aws/ecs_composex#302]
**Describe the bug**
If I have a sidecar container as part of a family which has `ecs.depends.condition: SUCCESS`, this sidecar is marked as essential and not the main container in the family.

This causes ECS to complain `Invalid request provided: Create TaskDefinition: A dependency container with SUCCESS or COMPLETE condition cannot be an essential container`

Note: this issue is masked if use_xray is true, in that case the xray container becomes the essential one.

**To Reproduce**
```  
  sidecar:
    deploy:
      labels:
        ecs.task.family: myfamily
        ecs.depends.condition: SUCCESS

  main:
    deploy:
      labels:
        ecs.task.family: myfamily
    depends_on:
      - sidecar
```
This results in the sidecar being marked essential and the invalid request error

**Expected behavior**
"main" should be marked essential in this case.
