### ISSUE TITLE
Add AWS CodeGuruProfiler support for our services

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#319]
**Is your feature request related to a problem? Please describe.**
As a developer I would like to be able to easily create a new CodeGuru profiling group to be created along my deployment.

**Describe the solution you'd like**
```
services:
  serviceA:
    x-x-ray: True|False # Already defined
    x-codeguru-profiler: True|False
```

```
services:
  serviceA:
    x-x-ray: True|False # Already defined
    x-codeguru-profiler: {} # CodeGuru profiler properties
```

**Describe alternatives you've considered**

```
services:
  serviceA: {}

x-codeguru_profiler:
  profileA:
    Properties: {}
    Lookup: {}
    Settings: {}
    Services:
      - name: serviceA
      - access: RW
```

**Additional context**
[AWS CodeGuru profiler properties](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codeguruprofiler-profilinggroup.html)
