### ISSUE TITLE
Support for x-elastic_cache

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#331]
**Is your feature request related to a problem? Please describe.**
As a developer I want to use AWS ElasticCache to deploy redis / memcache clusters.

For Redis specifically, it would be great to have an easy way to define Replica clusters as well as the main cluster.

**Describe the solution you'd like**
```
x-elastic_cache:
  clusterA:
    Properties: {}  # AWS::ElastiCache::CacheCluster Properties
    MacroParameters:
      ParameterGroup: {}
    ReplicationGroup: {} # AWS::ElastiCache::ReplicationGroup properties, only valid if Cluster is for redis
    Settings: {}
    Services:
      - name: serviceA
        access: RW
```
Similar to `x-rds` and `x-docdb`, access won't have a real impact. Given there is no password association, only the SecurityGroup Ingress is to be done.

**Additional context**
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-cache-cluster.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html
