### ISSUE TITLE
Authentication support with Cognito Pool on x-elbv2

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#338]
**Is your feature request related to a problem? Please describe.**
As a developer I have a user pool that allows me to authenticate users to applications.
I would like to be able to add a condition to rules that will allow me to require authenticated requests via an AWS Cognito pool

**Describe the solution you'd like**
```
x-elbv2:
  lbA:
    Properties: {}
    Settings: {}
    MacroParameters: {}
    Services: []
    Listeners:
      - Port: 8080
        Protocol: HTTP
        Certificates:
          - x-acm: public-acm-01
          - CertificateArn: arn:aws:acm:eu-west-1:012345678912:certificate/102402a1-d0d2-46ff-b26b-33008f072ee8
        Targets:
          - name: bignicefamily:rproxy
            access: /
          - name: youtoo:rproxy
            access: /stupid
          - name: bignicefamily:app01
            access: thereisnospoon.ews-network.net:8080/abcd
            cognito_auth: AuthenticateCognitoConfig

```

**Additional context**
[AuthenticateCognitoConfig](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listenerrule-authenticatecognitoconfig.html#cfn-elasticloadbalancingv2-listenerrule-authenticatecognitoconfig-userpoolarn)
