### ISSUE TITLE
x-docdb support for AWS::DocDB::DBClusterParameterGroup

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#340]
**Is your feature request related to a problem? Please describe.**
As a developer I might have to tweak some settings for docdb to work correctly as I intend to.
Therefore I need to be able to define AWS::DocDB::DBClusterParameterGroup for my cluster.

**Describe the solution you'd like**
```
x-docdb:
  db-01:
    Properties: {}
    MacroParameters:
      DBClusterParameterGroup: {} # AWS::DocDB::DBClusterParameterGroup Properties
```

**Describe alternatives you've considered**
```
x-docdb:
  db-01:
    Properties: {}
    DBClusterParameterGroup: {} # AWS::DocDB::DBClusterParameterGroup Properties
```

**Additional context**
https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbclusterparametergroup.html
