### ISSUE TITLE
for x-rds, allow to export specific keys of the secret directly to the service.

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#351]
**Is your feature request related to a problem? Please describe.**
With Fargate 1.4.0 and on EC2, ECS Supports to expose specific keys of a SecretsManager Secret (JSON formatted) to the container.
This can be very useful to expose well known parameters to a container expecting it.
Given that for RDS the secret format is well known, one might want to be able to expose each part of the secret in its own keys.

**Describe the solution you'd like**
```
services:
  serviceA: {}
x-rds:
  dbA:
  Properties: {}
  MacroParameters: {}
  Settings:
    EnvNames: []
     SecretsMappings:
       - SecretKey: host
         VarName: DB_HOST
       - SecretKey: username
         VarName: DB_USERNAME
```

**Describe alternatives you've considered**
This syntax allows to define a per-service level secret exposure.

```
services:
  serviceA: {}
x-rds:
  dbA:
  Properties: {}
  MacroParameters: {}
  Settings:
    EnvNames: []
  Services:
    - name: serviceA
      access: RW
      SecretsMappings:
        host: DB_HOST
        username: DB_USERNAME
        password: DB_PASSWORD
```
