### ISSUE TITLE
RdsClusterParameterGroup not used for new DB

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#354]
**Describe the bug**
Using x-rds for a new DB via Properties (not via MacroParameters), ComposeX still creates a new `RdsClusterParameterGroup ` but does not assign it to the Cluster. If property is omitted, the parameter group should be assigned to the target cluster.

**To Reproduce**
```
x-rds:
  wordpress-db:
    Properties:
      Engine: "aurora-mysql"
      EngineVersion: "5.7"
      BackupRetentionPeriod: 1
      DatabaseName: wordpress
      StorageEncrypted: True
      Tags:
        - Key: Name
          Value: "dummy-db"
    Services:
      - name: wordpress
        access: RW
        SecretsMappings:
          Mappings:
            host: MARIADB_HOST
            port: MARIADB_PORT_NUMBER
            username: WORDPRESS_DATABASE_USER
            password: WORDPRESS_DATABASE_PASSWORD
            dbname: WORDPRESS_DATABASE_NAME

```
