### ISSUE TITLE
Parameter not passed for S3 Bucket Service Access

### ISSUE THREAD

**Issue by jackqu7** [lambda-my-aws/ecs_composex#355]
**Describe the bug**
If a service is given access to an x-s3 bucket, CF fails because the service template is not passed the bucket name/ARN parameters

**To Reproduce**
```
x-s3:
  test:
    Properties:
      BucketName: test
      AccessControl: BucketOwnerFullControl
      ObjectLockEnabled: True
      PublicAccessBlockConfiguration:
          BlockPublicAcls: True
          BlockPublicPolicy: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: False
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "aws:kms"
      VersioningConfiguration:
        Status: "Enabled"
    Services:
      - name: myservice
        access: RWObjects
```

CF fails: 
`myservice	UPDATE_FAILED	Parameters: [testArn, test] must have values`

Caused by root template not passing these parameters to service template.

**Expected behavior**
Service template passed S3 parameters.
