### ISSUE TITLE
Custom FeatureName for RDS

### ISSUE THREAD

**Issue by jackqu7** [lambda-my-aws/ecs_composex#375]
**Is your feature request related to a problem? Please describe.**
#373 introduces support for RDS features to access S3 but this is limited to s3Import currently. I would like the feature s3Export instead.

**Describe the solution you'd like**
Feature names mentioned explicitly then associated with resources to create role.
```
Features:
  - Name: s3Export
    Resources:
      - bucketA
      - arn:aws:s3:::bucketB
```

**Additional context**
Feature names vary by EngineVersion and are not explicitly documented, use eg `aws rds describe-db-engine-versions --engine aurora-postgresql` to find all feature names.
