### ISSUE TITLE
Support for local volumes

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#390]
**Is your feature request related to a problem? Please describe.**
As a developer I might have more than one container which I would like to share a volume with (non EFS).

**Describe the solution you'd like**
```
volumes:
  local-01:

services:
  A:
    volumes:
      - local-01:/var/tmp
   B:
     volumes:
       - local-01:/var/someotherpath
       
    C:
      volumes:
        - local-01:/var/someotherpath
```

(B & C services are in the same task definition therefore the volume would be shared)

**Additional context**
https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-volumes
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-volumes.html
