### ISSUE TITLE
Look up for security groups

### ISSUE THREAD

**Issue by krishin-js** [lambda-my-aws/ecs_composex#393]
**Is your feature request related to a problem? Please describe.**
Given I have to add ingress rule by specifying a security group
Then I am forced to hard-code it's value.

**Describe the solution you'd like**
If a look-up is implemented for security groups, then the above requirement could be implemented as follows:

Given I have to add ingress rule by specifying a security group
When I use look-ups for security groups
Then I can reference the security group in my ingress rule

Alternatively, is there a way to provide generic solution for look-ups where we would need to specify the type as the main parameter (in this case security-group) followed by any other parameters which would be required to support it?

**Comment by JohnPreston** [comment]
Hi @krishin-js 
Thanks for the feature request.

We could extend the `Ingress` for SecurityGroups as follow?

```
services:
  A:
    x-network:
      Ingress:
        AwsSources:
          - Type: SecurityGroup
            Lookup:
              Tags: []
              RoleArn: <>

```
To allow the same lookup functionalities as per other AWS resources.
That way you do not need the ID hardcoded, you can lookup via tags and if need be use the RoleArn to assume another set of permissions to identify the resources?
