### ISSUE TITLE
Enable X-Ray

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#56]
**Is your feature request related to a problem? Please describe.**
I want to be able to do the analysis of my application performance via XRay.

**Describe the solution you'd like**
Via the service configs (local and/or global) I would be able to indicate whether or not I want the AWS XRay container to be running as part of my task definition

```
configs:
  composex:
    use_xray: False

services:
  serviceA:
    configs:
     use_xray: True
```

**Describe alternatives you've considered**
In the CLI, add `--enable-xray` would override configuration settings and set to true for all.

**Additional context**
The X-Ray container should be contained to the minimum compute footprint possible.
