### ISSUE TITLE
Support Docker Labels for configuration

### ISSUE THREAD

**Issue by c-py** [lambda-my-aws/ecs_composex#78]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have multiple containers in a single task, such as a ngnix webserver container and java application server container.

**Describe the solution you'd like**
Leverage docker [labels](https://docs.docker.com/compose/compose-file/#labels-2) to annotate which ECS service and cluster a container belongs to, so it can be placed into the same task defintion

Example:
```
nginx:
    image: nginx
    labels:
      ecs.service: myapp
java:
	image: springboot
	labels:
		ecs.service: myapp
```

**Describe alternatives you've considered**

**Additional context**
I believe this design pattern can be extended to annotate which sqs queues are in use, and also ECS specific parameters such as task CPU and memory configurations.

**Comment by JohnPreston** [comment]
Thanks @c-py  for the FR, great suggestion!!

Would you use the [AWS ECS Task Definition `Family`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-family) property to reflect that as a single task coming together for the service?

```
services:
  nginx:
   image: nginx
   labels:
     ecs.task.family: myapp

 app:
  image: app_image
  labels:
    ecs.task.family: myapp
```
