### ISSUE TITLE
Refactor the Load-Balancing config to enable more settings.

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#79]
**Is your feature request related to a problem? Please describe.**
I want to be able to define extra settings for the ALB or NLB which points to my container.
Instead of using booleans for use_alb / use_nlb, I would prefer to have a configuration object, containing a variable lb_type value set to network or application.

**Describe the solution you'd like**
```
services:
  serviceA:
    configs:
      network:
        ingress:
          lb_type: application
          acm: use::blah # example of extra settings.

```
**Additional context**
