### ISSUE TITLE
Duplicate environment variable key

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#82]
**Describe the bug**
Setting an EnvName on a resource (ie, SQS queue) and have the same environment variable on the service, ECS ComposeX doesn't use the one from the service but has two environment variables with the same name.

**To Reproduce**
```
services:
  targetone:
    image: ${SFTP_TRANSFER_IMAGE}
    environment:
      QUEUE_NAME: targetonequeue


x-sqs:
  targetonequeue:
    Properties: {}
    Settings:
      EnvNames:
        QUEUE_NAME: targetone
    Services:
      - name: targetone
        access: RWMessages

```
**Expected behavior**
Only one environment variable should be set, and it should use the one coming from the x-resource.
