### ISSUE TITLE
For well known images, replace with the x-section accordingly.

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#84]
**Is your feature request related to a problem? Please describe.**
If I use a docker image like `postgres` or `redis` which are well known ones, I would like ecs composex to interpolate with x-resources (namely RDS or elastic cache)

**Describe the solution you'd like**
```
services:
  db:
     image: postgres
     config:
       composex:
         xreplace: true
```

Results into

```
x-rds:
  db:
    Properties: {}
    Services: []
    Settings: {}
```
