### ISSUE TITLE
Allow support for ACM SSL cert for publicly exposed services.

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#93]
**Is your feature request related to a problem? Please describe.**
* When I already have a public DNS Zone, I provide with its ID
* I indicate what public hostname I would like the family/service to be published on
* ACM creates a public certificate for it that gets automatically validated by Route53 record.
* If I already have a public DNS Namespace I pass the namespace ID and the service gets registered there whereas the 
certificate is added to the route53 zone.

[ACM properties page](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html)

**Describe the solution you'd like**
```

x-acm:
  publicApp:
    Properties: {}
    Settings: {}
    Services:
      - name: serviceA
        ports: [443]

services:
  serviceA:
    x-configs:
      network:
        lb_type: application
        is_public: True
```
